# Generated by Django 4.0.6 on 2022-08-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
