# Generated by Django 4.0.6 on 2022-08-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
